---

# Main tasks file for iptables-persistent role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::iptables-persistent'
    - 'role::iptables-persistent::init'

- name: 'INSTALL | Manage OS family specific installation tasks'
  become: True
  include_tasks: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::iptables-persistent'
    - 'role::iptables-persistent::init'

- name: 'CONFIG | Manage configuration'
  become: True
  include_tasks: "{{ role_path }}/tasks/configure.yml"
  tags:
    - 'role::iptables-persistent'
    - 'role::iptables-persistent::init'
